### ISSUE TITLE
Static Form convert to Editable PDF

### ISSUE THREAD

**Issue by SreekanthMekala** [galkahana/HummusJSSamples#16]
Great to see kind interesting work!!!!

Am just checking that static PDF form to convert editable(textbox and checkbox) PDF form like attached PDF. How can we achieve this?

[form-2.pdf](https://github.com/galkahana/HummusJSSamples/files/1973447/form-2.pdf)

In your example, The data filling in static PDF form and generating output PDF file, We are just looking something send static PDF form and output should be Editable PDF form file.

Thanks in advance.

**Comment by galkahana** [comment]
well, you will need to build a from object on top of the static graphics. This requires building an AcroForm object and tie it to the document catalog. there's a little bit of PDF knowhow to capture in order to build this. refer to the PDF reference manual. Hummus can provide you with the underlying building blocks to build the necessary elements.
