### ISSUE TITLE
text-extracion.js code duplication

### ISSUE THREAD

**Issue by antonmok** [galkahana/HummusJSSamples#2]
Hello,

I found this code in text-exxtraction.js line 17

`if(extGState.getType() === hummus.ePDFIndirectObjectReference) {
                    extGState = pdfReader.parseNewObject(extGState.toPDFIndirectObjectReference().getObjectID()).toPDFDictionary();
                }
                else {
                    extGState = pdfReader.parseNewObject(extGState.toPDFIndirectObjectReference().getObjectID()).toPDFDictionary();
                }`

Both `if` branches performs the same code.

Should there be some differences depends on `extGState` type or `if` is not necessary?

**Comment by galkahana** [comment]
there should be a difference, yes.
in pdf an object can be associated to a dictionary in two ways:
1.  object can be contained in a dictionary.
2. an independent object that is referenced from the dictionary.

the first case of the if statement should handle case 2, the else case 1.
code however assumes its a reference in both.
should be corrected so that else simply converts the object to a dictionary.

fixed it now:
https://github.com/galkahana/HummusJSSamples/blob/master/text-extraction/lib/text-extraction.js#L21

**Comment by antonmok** [comment]
Thanks a lot!
