### ISSUE TITLE
Support CID fonts

### ISSUE THREAD

**Issue by antonmok** [galkahana/HummusJSSamples#7]
Hello Gal,

I have PDF file which contains CID fonts and I could not extract text from it using your text-extraction lib.

If I correctly understand you need such files for further development.

"If you find me an example file that doesn’t bring the text (but also doesn’t crush the code), it’s probably an example of such a file - and you’ll have my thanks if you send it to me."

You can download it here:
https://www.dropbox.com/s/6x9zrc6cd75l3as/publication_1284_original.pdf?dl=0

It would be great if you give some advices about how to handle such fonts.

**Comment by galkahana** [comment]
to quote: 

"For full details on how to translate char codes to text look into 5.9.1 Mapping Character Codes to Unicode Values.

If you want to know why i got a limitation in the code, it is because i didn’t want to bother and look for all them predefined Cmap files. Just looking at the size of the table made me dizzy. Plus there’s this very convenient ToUnicode map normally, so why bother. well there’s a good reason - cause we need the writing direction, which is why we’re limited to horizontal writing."

Best is if you go and read 5.9.1 section in the PDF manual.
the font-decoding.js script in the sample, and more specifically https://github.com/galkahana/HummusJSSamples/blob/master/text-extraction/lib/font-decoding.js#L327 simply follow up on the instructions there.

Note, that as these instructions say - for some PDFs you cant recreate they text from the glyph. it might be that this is the case with the sample PDF. try opening it in acrobat and copying some text sections that the script doesn't grab. then paste them somewhere - you may be getting gibbrish. it might mean that the text cant be translated at all.

**Comment by galkahana** [comment]
yeah. in the case of this pdf you cant really extract the text. cid fonts are encoded with identity-h which is private encoding and does not provide textual meaning to glyphs. so even extending the algorithm to support CID fonts as explained in 5.9.1 won't help.

**Comment by antonmok** [comment]
Thanks for explanation.
